### ISSUE TITLE
Vercel GDPR

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#108]
https://www.adsimple.at/datenschutzerklaerung/externe-onlineplattformen-einleitung/vercel-datenschutzerklaerung/

https://dev.to/mandrasch/how-to-host-sveltekit-ssr-apps-gdpr-compliant-15bh

**Comment by KonradUdoHannes** [comment]
Will we be able to solve the GDPR concerns wrt. Vercel, as it is intrinsically a US company and they will probably not make any special exceptions for CorrelAid?

On the other hand I'm wondering how GDPR relevant the Vercel service is, as they are only hosting the website and not the data. The website itself is probably not GDPR relevant, and the only issue I see here is the processing of data posted by users. Although transient, that data would probably go through the vercel backend server. I don't know however, how much of a difference this makes wrt. GDPR. But in practical terms I suspect that it reduces privacy violations risks quite a bit.

To be 100% GPDR compliant would probably require to switch to a european solution such as IONOS or Hetzner. If desired I could help with that.

**Comment by jstet** [comment]
The point about the data not being hosted on Vercel makes sense yes oups. However that changes probably if we do #100 . But if we do #100, hosting the website is easy and we could just set up something on Azure  (we have credits there) on a European server

**Comment by jstet** [comment]
Vercel is GDPR compliant according to their FAQ. data displayed on website is not relevant for GDPR.
