### ISSUE TITLE
Link to partner when clicking on image is missing

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#112]
#104
already added the link to the graphql query

**Comment by KonradUdoHannes** [comment]
@jstet does this close the issue? Or is there anything else to do here?

**Comment by jstet** [comment]
Sry wrote the issue before pushing 2a1fdd2240b7eac6e07252f5d6ea940e3c77ab4e

No doesnt close the issue, because the link is still missing but the link data is part of the api request now.

**Comment by KonradUdoHannes** [comment]
Ok then I think I understand the issue. The link is already provided by the CMS, but on the svelte side it still needs to be correctly used by the by the partner route and or the `Person` component from `lib` that is used. I'll pick up issue if that is ok.
