### ISSUE TITLE
configure fromatting and linting for the project

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#113]
Currently there is not formatter and linter set up for the projects. The goal is to
- add a formatter and a linter
- add svelte plugins for the formatter and the linter
- ensure that the configuration of formatter and linter is consistent
- create script commands for running the formatter and the linter
- set up a configuration consistent with the current code base. Possibly ignoring some systematic rules that are harder to fix automatically, such that linting output is helpfull and not overwhelming.

**Comment by KonradUdoHannes** [comment]
WIP in #114. @jstet could you have a look at the differences in the PR in particular at the files `src/routes/+layout.svelte` and `src/lib/js/helpers.js` which I used as examples for the current configuration of the formatter. I think we should loosely agree on the configuration of the before applying it systematically across the project. Personally I don't care too much about specific details, but believe that the consistency gained by the formatting tool is the biggest gain in the end even if specific situations might be debatable.

The most striking change is the indentation level of 2 (although helpers already has it). This is often used with html/js and by extension svelte and makes everything quite a bit more compact, but I don't want to force it on the project if you (@jstet) don't like it at all.

Formatting also breaks a few inline html comments, by moving them to the next line. This does not make sense logically and I would fix it once we agree on the rest of the formatting. Also once we agree on the formatting I would apply it to all the files making sure that the PR does not contain any other changes wrt. content, because the would be impossible to find in the difference view.

**Comment by jstet** [comment]
Thank you @KonradUdoHannes ! Had a look at the changes and I am fine with the styling and you are very welcome to implement it.

**Comment by KonradUdoHannes** [comment]
#114 is ready for review and includes a consistent formatting/linting configuration. Wrt. to linting the following remarks should be made.

- jsdoc specific errors are turned off as they don't fit to the codebase right now
- camelcase errors are turned off as the don't fit the codebase and fixing them has high risk/return ration (hence low priority)
- there are many unused var errors that should still be addressed and that have a high potential for bugs either now or in the future. This should be done carefully as a seperate issue/PR
- linting/formatting has a bit of an issue with the embedded graphql queries. Some queries have been excluded from formatting for that reason. As it would be good practice not to embed the queries eventually not too much effort should be placed here.

**Comment by KonradUdoHannes** [comment]
PR #114 has been merged and the remaining linting issues are contained in #118. Therefore this gets closed.
