### ISSUE TITLE
Links of top nav should be coloured (only) when a user is on the corresponding page

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#121]
Similar to the bottom nav: when a user is on an about us page, about us is blue.

Code for this: https://github.com/CorrelAid/correlaid_website/blob/main/src/lib/layout/Header.svelte#L175

**Comment by jstet** [comment]
Links stay green at the moment:
![2023-04-26_10-12](https://user-images.githubusercontent.com/67161972/234512659-265b8dc1-db8a-4626-953a-b8ac643e9bea.png)

**Comment by jstet** [comment]
I am very to reopen this issue again, but the top nav links still stay green when you click on the correlaid logo

**Comment by KonradUdoHannes** [comment]
@jstet no worries if its not done its not done. I think its also a good process, because I believe thinking of all edeg cases on the spot is actually a lot harder then reopening an issue when they pop up.

**Comment by jstet** [comment]
Same issue for the bottom nav btw

**Comment by KonradUdoHannes** [comment]
I've imlpemented the solution, which is very simple, but I'm not able to currently check whether it fully works because I only have a tablet screen size right now. The fix is in #192.

@jstet if its urgend you can look at the PRs deployment, and if it works merge it. Otherwise I'll check and merge it on Sunday.

**Comment by jstet** [comment]
Does not work :S 
![2023-04-29_01-05](https://user-images.githubusercontent.com/67161972/235267681-db8218b5-ef96-48a0-a5dd-e14ed04c4c5d.png)
Also, when refreshing the page, the color disappears.
