### ISSUE TITLE
Restructuring Components

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#146]
### Avatar
- Used in component: Person, Volunteer_Journey
### Blog_Card
- Used on page: home, blog, podcast
### Box
- Used in component:  Text_Container
- Used on page: Projects (Slug), CorrelAidX overview
### Card
- Used on page: Projects Overview, Education Resources, CorrelAidX (Slug)
### Carousel
- Used on page: Comunity
### CTA
- Used in layout
### Events_Card
- Used on page: home, events, correlaidx (Slug)
### Hero
- Used in components: Carousel
- Used on pages: correlaidx (Slug)
- Used in layout
### Html
- Used in components: Carousel, CTA, Text_Container, Timeline, Volunteer_Journey
- Used on pages: team, events(slug), projects (slug),  blog(slug), correlaidx(slug)
- Used in layout
### Link_Button
- Used in components: CTA, Hero, Header,
- used in layout components: MobileDrawer
### Links
- Used in components: Person
- Used on page: projects (slug)
### Map
- used on page: CorrelAidX
### Modal
- used in component: Volunteer Journey
### HeaderBottomNavButton
- used in layout comp: Header Bottom Nav
### Partner
- used on page: partners
### Person
- used in layout
- used on pages: values, team, consulting, blog(slug), volunteer_journeys
### Quote_Carousel
- used in layout
### Timeline
- used in layout
### Text_Container
- used on pages: events(slug), blog(slug), projects(slug)
### Volunteer_Journey
- used on pages: volunteer journey

**Comment by KonradUdoHannes** [comment]
@jstet since this seems to be a very large issue (or at least open ended in its formulation), feel free to break it up into some subtasks and assign some to me.

**Comment by jstet** [comment]
I think this is issue is better split up if restructuring needs arise again
