### ISSUE TITLE
FAQ component: old Projects FAQ probably not doable with WYSIWYG component 

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#156]
See bottom of: https://www.correlaid.org/en/nonprofits/projects/

We need a FAQ component. This needs to be added to directus as well.

**Comment by friep** [comment]
@jstet don't worry too much about this for now: we're still in the process of rewriting the content so i'm not 100% sure the steps are needed.

**Comment by friep** [comment]
closed as not needed content - wise, at least for projects
