### ISSUE TITLE
refactor membership application page to not use svelte-kit form actions

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#182]
This is a subtask of #100. The membership application page uses a svelte-kit form action in order to process its form data. This action does not appear to be strictly needed, but seems to originate from the use of the `felte` library for working with forms. This can probably be refactored by providing a callback directly to the forms `onSubmit` event.

**Comment by KonradUdoHannes** [comment]
The membership_application pages was currently excluded explicitly from the prerendering list in `svelte.config.js`. When the refactoring is done this explicit removal should also be removed.

**Comment by jstet** [comment]
I moved the membership application to a dump folder temporarily as this is not a prio right now
https://github.com/CorrelAid/correlaid_website/commit/37ea5c4d842c795e12da617f0d80fb1eacb67f54

**Comment by jstet** [comment]
As #94 is closed, we can close this as well
