### ISSUE TITLE
Search/Filter Bar

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#209]
connected to #148

Blog Posts, Projects, Podcasts, Workshops and Events could use a search/filter bar

**Comment by LtSalt** [comment]
From a design perspective, a search bar could be easily added to blog posts and events. For example, we could place it next to the headers and right aligne it. The other subpages would require some design decisions. Maybe it would be useful to split this into two issues?

From a functional perspective, searching for post / event titles could be a manageable first step. I don't know about the overhead of full text search and as far as I can see, we have not yet assigned tags.

**Comment by KonradUdoHannes** [comment]
Just to clarify the goal of this issue. do we want to search posts, projects, etc. Individually (on their respective pages) or do we want search functionality, in the header for instance, that searches the entire correlaid website at once?

**Comment by jstet** [comment]
I personally vote to add search functionality to the respective pages first and maybe we can add global search functionality later

**Comment by jstet** [comment]
Filtering has to happen client side because of the static build.
