### ISSUE TITLE
blog shows english version although there is none 

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#217]
[This post ](https://correlaid-website.vercel.app/blog/sexy-daten/) is available in English (although without content) even though there is no translation in the [translations collection](https://cms.correlaid.org/admin/content/Posts_translations).

**Comment by jstet** [comment]
There was an english version in the Posts translation collection, but completely empty, idk what happened. I deleted it and now it shows the correct versions. Will test what happens with i add english text but then delete it again.

**Comment by jstet** [comment]
yes when i add text and then delete it again, the translation is not deleted

I'll add something to check for empty translations
