### ISSUE TITLE
Website crashes when Content Creator Person is not published

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#222]
I created a new content creator but had to create the person in People for it first. 
The default status of a new person is draft and i forgot to change it to published.
i could then create my content creator and publish it. 
Website then crashed because person_id was null. (see screenshot)

maybe something that can be solved UX-wise in directus (note when creating a new person)? 

![Screenshot 2023-05-04 at 12 46 05](https://user-images.githubusercontent.com/13187448/236183081-7abb6444-d94a-4e34-a450-17faeafe2c26.png)

related to #204

**Comment by KonradUdoHannes** [comment]
also related to #23, where the goal is that faulty content will not crash the site anymore but log and ignore the content problems and continue with the rest.

**Comment by jstet** [comment]
fixed in #255
