### ISSUE TITLE
Handle projects without proper description

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#232]
Right now, the Konstanz and the SOG project have no proper description , resulting in an empty page : https://correlaid-website.vercel.app/daten_nutzen/projekte/2020-10-ODK/ 

is this a directus thing (ie. should those projects not be public) or do we need a way to also display projects without a dedicated subpage? 

related: #231 , #211

**Comment by friep** [comment]
if not enough time for pre-launch, i suggest quick-fix by unpublishing projects in directus.

**Comment by jstet** [comment]
We could add a field that determines whether a project has its own page and visualize this somehow in the projects overview.

**Comment by jstet** [comment]
Did that
