### ISSUE TITLE
Add trigger to build website as directus workflow

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#239]
#40

**Comment by KonradUdoHannes** [comment]
I think an important question here is how to deal with errors during static building. In particular I think the following questions are important.
- Which errors should be handles such that the new build completes.
- Which errors should stop the build process, so we don't build a faulty website.
- Who gets informed if the build process fails, and how?

I think with good configuration we can ensure that directus issues don't affect the site, except that it might be slightly outdated. At the same time we have to ensure that we don't end up in a situation where the automated build has been failing for a long time and nobody noticed.

**Comment by KonradUdoHannes** [comment]
This also affects #24 as I will probably introduce environment variables to control the error handling, such that the build workflow can have a different configuration than the non-static site for cms testing.

**Comment by jstet** [comment]
Workflow added, it triggers an action to run. This action could contain the steps u mentioned. However, if the build fails, cloudflare keeps the old deployment online.

#281
