### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#25]
- [ ] Sitemap (see https://scottspence.com/posts/make-a-sitemap-with-sveltekit)

**Comment by KonradUdoHannes** [comment]
As SEO is a complex topic I'll attempt to split this up in this task and ask others for help with many of the related tasks. The starting point is to analyze the production site with tools for seo analysis. Some of these tools have free online versions that analyze websites, and I think this is a good starting point for us and we should address the major finding of these free tools. Only afterwards does it potentially make sense to invest into paid tools (use trial periods etc.)

The free tools I've been using so far are 
- https://suite.seotesteronline.com
- https://smallseotools.com
- https://www.seobility.net/en/seocheck/

The first list of ToDo's is the following.
- Forwards from old site #334
- Missing meta description  #336
- Missing <h1> Tag #337
- Use semantic tags (lower prio, except for the h1 above). #338
- SEO firendly internal URLs #339
- Longer page title #340

**Comment by KonradUdoHannes** [comment]
I repeated the free checks on the main page and we had some improvements. It seems that free tools don't capture the full page as svelte dynamically inserts some parts into the dom. So the tools still don't find our h1 tags (even though we do have them now). There is only few explicit to-dos left for now. We could still do the site map.

**Comment by KonradUdoHannes** [comment]
I'll move the sitemap creation to a separate backlog task for the following reasons.
According to [google's documentation](https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview), sitemaps are not as relevant if the sites are less than 500 internal pages large and and well linked internally. Our static build already creates a list of all routes so it is easy to extract the number of internal sites, and we are currently at 174, so well below 500. Internal linking is also good imho.

The sitemap issue is #406

**Comment by KonradUdoHannes** [comment]
Closed, because all linked issues that are not in the backlog are done.

**Comment by jstet** [comment]
- [ ] add h1 to starting page
https://freetools.seobility.net/en/seocheck/correlaid.org
