### ISSUE TITLE
CTA groups are not translated

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#301]
CTA groups (e.g. landing page or newsletter page) are only shown in German.

**Comment by friep** [comment]
probably something to do with directus as i get German data back in the network tab.

**Comment by KonradUdoHannes** [comment]
Currently the fetched language for cta_groups is hardcoded to german and not related to the selected language of the site. I can change it wrt to the fetching, which either fixes it or turns the rest of the work into a pure directus issue.
