### ISSUE TITLE
Remove unused files and comments

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#302]
As it is good practice for versioned projects, unused files and commented out code blocks should be removed from the current state of the project. In theory these are easily restored if needed. In practice it can be a little difficult to find the corresponding commits, particularly if the entire file has been removed and file specific commit histories are not available. To help with this the removal should be accompanied with an annotated tag just prior to the removal commit. The tag annotation should clearly state what is to be removed. This will allow to later easily checkout the entire tag or specific files from it.

Currently I already have the following suggestions for removals
- the dump folder
- the carousel component (not used)
- the volunteer journey route (entire file commented out)

@jstet are you fine with the suggested approach?

**Comment by jstet** [comment]
Makes sense I am fine with this!
