### ISSUE TITLE
Navbar: clicking "Projekte" (daten_nutzen/projekt) makes dropdown uncloseable

### ISSUE THREAD

**Issue by pr130** [CorrelAid/correlaid_website#318]
this is a weird bug where clicking "Projekte" submenu of "Daten nutzen" makes the dropdown stick. I am then not able to close the dropdown nor can I open other pages -> the URL changes but the page doesn't load. 

only reloading the website resolves the issue.

**Comment by friep** [comment]
maybe this is not reproducible? i don't know.. something is weird here ... 👀
