### ISSUE TITLE
How to handle public projects from CorrelAidX chapters that are not active anymore

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#319]
When a local chapter has a published project but is not active (and hence not published) anymore, the following error is thrown and /using_data/projekte cannot compile: `Uncaught (in promise) TypeError: l[12].Local_Chapters_id is null` 

@IsabelWi what do you think? i'd like to keep the reference in the "project database" because otherwise we lose this information/data point 

@jstet / @KonradUdoHannes would it be possible to add status `inactive` on LCs so that they are returned to you and you can display them in the ProjectCard but without link? 🤔

**Comment by IsabelWi** [comment]
we can still make the inactive chapters appear so that the projects remain visible. I can otherwise adjust the affected texts or we can use this get active box with the hand heart icon and place a permanent volunteer call there - I'll try that out.

**Comment by friep** [comment]
closing for this non-technical solution :)
