### ISSUE TITLE
Missing h1 tag

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#337]
The website currently does not have an h1 tag, which is considered bad from a SEO perspective. It should be analyzed where to reasonably include an h1 tag. The point is not to necessarily add new content, but to possibly use the h1 tag for something that is the main headline anyways.

**Comment by friep** [comment]
2 things:

- maybe the hero title could be the h1 ? if that's hard to do design-wise, maybe we can replicate them but make them hidden? or do they need to be visible? 
- for the "subpages" we already use h1 but have multiples... e.g. https://preview.correlaid.pages.dev/daten_nutzen/projekte/ is this bad practice or ok?

**Comment by KonradUdoHannes** [comment]
I'll look into both. But regarding the first point, I don't think hidden h1s should be introduced. 

One of the guiding principles in SEO is to make the site for humans first of all and not for the search engine, so introducing hidden fields should not be the way to go. If we don't have any h1 to begin with we also have all the freedom in the world in terms of styling it so, meaning anything can be the h1. Or to put differently we probably already have it just not with the tag. I'll look into the hero title for this purpose.

**Comment by KonradUdoHannes** [comment]
I replaced the h2 tag in the hero component with an h1 tag. Styling wise this makes not difference, as all the tailwind classes simply stayed the same, but we now more consistently have an h1 tag on every page that uses the Hero component.

**Comment by KonradUdoHannes** [comment]
A quick we search indicated that there is no issue in having multiple h1 tags wrt. to SEO. There seem to be some debate about whether it should be best practice or not, but that basically means it currently is not best practice if people cannot agree on it. So I think our current setup is fine wrt. headings.
