### ISSUE TITLE
Umlaute in URLs?

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#349]
are umlaute in URLs a problem?

e.g. https://preview.correlaid.pages.dev/community/correlaidx/%C3%96sterreich/

**Comment by KonradUdoHannes** [comment]
Should not be an issue fundamentally. The browser will take care of the url encoding and will translate non-ascii characters into their URL encoded version. If I click on the link for instance, my browser immediately shows the "Ö" again.

That being said, there is however a slightly higher risk of bugs as any business logic that involves comparisons on the affected part of the url has to be sure whether it is currently HTML encoded or not. Meaning any string comparison `"Ö" === "%C3%96"` would fail even though the terms have equivalent meaning. It might be that svelte-kit already takes care of this in the background, but even if it  doesn't I don't think it should prevent us from allowing Umlaute and possibly implementing URL decoding explicitly.

**Comment by friep** [comment]
thanks for the explanation. right now, it's a bit inconsistent across pages (muenster vs österreich) but i'm fine with that. :)
