### ISSUE TITLE
Open external links in new tab

### ISSUE THREAD

**Issue by MKyhos** [CorrelAid/correlaid_website#382]
While navigating and using a website, it can be neat if external links (e.g. to the betterplace website) open by default in a new browser tab, instead of the current one (such that one has to use the browser "back" button to continue on the initial page).

[Here](https://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/) is a lengthy argument.

In case the maintainers agree, this would imply the following To-Do:

- for all external links, add `target='_blank'`. For internal links, it should remain the default (`target='_self'`). For reference, see [here](https://www.w3schools.com/tags/att_a_target.asp).

Thank you very much and big congrats to the launch! :rocket:  Have a nice holiday everyone :)

**Comment by KonradUdoHannes** [comment]
Currently we don't have a consistent setup in this regard. I think it would be very good if we manage to systematically implement it as suggested. For this we need to collect all the locations of external links. I see the following
- [x] Partners (already uses target blank)
- [ ] Social Media in Footer (`lib/layout/Footer.svelte`)
- [ ] Social Media when displaying people (covered by `lib/components/Links.svelte` I think)
- [ ] partially Project links (`lib/components/ProjectLinks.svelte`)
- [ ] event registration link (`routes/[[locale=locale]]/[events=events]/[slug]/+page.svelte`)
- [ ] podcasts (uses "external" BlogCards `src/lib/components/Blog_Card.svelte`)
- [ ] Link Buttons (as already addressed in #383, but where are they used externally?)

We can of course always fix remainders later, but this should already cover a lot of the external links. If anybody finds more, lets add them to this issue so we can track it.

**Comment by KonradUdoHannes** [comment]
I created separate issues for the different links in the above list to make it easier to contribute to this task and to split this task between people. @MKyhos do you want to take over #400, which fits your draft PR?
