### ISSUE TITLE
Move all cms parsing server side/into the static build

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#389]
Currently some of the cms data parsing happens on the client side and some on the server side. Moving all the parsing to server side has the advantage that possible parsing errors happen at build time for the static side build. Otherwise the data, that cannot be parsed, is stored inside the static build and fails parsing every time the user opens a particular subpage. Server side parsing therefore prevents deployments of faulty parsing logic or deployments at times of inconsistent cms data.

Some components of the page already parse on server side. Namely
- The top level page builder (in `routes/+layout.server.js`)
- all "slug pages", i.e. blog post pages, local chapter pages, event pages and project pages

The goal should be that all other pages that fetch data from directs also parse it on the server side as well. This can be identified with  a grep for `directus_fetch`.

Side note: Parsing on the server side has the disadvantage for content creators, that problems in the cms will cause http 500 errors and/or only log issues on the server side and not in the web browser. So either content creaters deploy a local copy of the site, or we'll have to make the 500 errors for dev more verbose.

**Comment by jstet** [comment]
We could also introduce another env var that allows switching between server side and client side parsing
