### ISSUE TITLE
 CI/CD-Pipeline

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#40]
- Set up branches that cause different deployments mechanisms
-  How to integrate with directus?

**Comment by jstet** [comment]
Depends on #100 and  #115 I think.

Suggestion:
Completely prerender the website for production so that its stable and not dependent on Directus (CMS) anymore. However host a dynamic preview version where you can immediately see changes made in the CMS.

**Comment by jstet** [comment]
Netlify has password protection. 
We could set up a preview branch and host it on Netlify. Pushes to main cause the website to be built statically.

**Comment by jstet** [comment]
We could use caddy on a vps on azure to host the static site: https://ellen.dev/serve-static-site-using-caddy.html

**Comment by jstet** [comment]
no index for preview page

**Comment by KonradUdoHannes** [comment]
@jstet do you need help here. I think right now you are credential wise the only one who can set it up. At the same time I think it would be good to get the static site deployment process up and running such that we can ideally switch the testing efforts from the helpers to the static site/process as this is the ultimate target

**Comment by jstet** [comment]
I think I m good thank you! Will treat this as a priority

**Comment by jstet** [comment]
Vercel production is now static.

**Comment by jstet** [comment]
Will test https://developers.cloudflare.com/pages/platform/preview-deployments/ for access control to previews however.

deploy hooks: https://developers.cloudflare.com/pages/platform/deploy-hooks/

**Comment by KonradUdoHannes** [comment]
I made an issue for end to end testing and we might want to include it in the CD for the static build, but lets discuss this. See #240.

**Comment by jstet** [comment]
This can be improved and is probably always a work in progress, but lets open issues sep issues when stuff comes up. Next step would probably be: #281 

Theres a preview website and a production website. CHanges on directus can immediatly be seen on the preview website. THe static production website can be built manually from directus but is also built periodically each day. From directus a gh action is triggered that runs tests and then sends a webhook to cloudflare to build page.
