### ISSUE TITLE
Improve Documentation for Collab

### ISSUE THREAD

**Issue by LtSalt** [CorrelAid/correlaid_website#418]
As someone who has little to no experience collaborating with others, I would find it helpful to follow an internal wiki / documentation / guidelines. 

In Correlaid's rlernen-planning-coding channel, we've talked about modifying and reusing [this wiki](https://github.com/selinaZitrone/github_workflow/wiki/2-Github-workflow) within an internal meta [ressources repo](https://github.com/CorrelAid/project-resources). I suggest going forward with it.

**Comment by KonradUdoHannes** [comment]
Apparently I didn't realize that GitHub auto generates TOCs for about two years now 😂. Anyways I'll start making a "How to Contribute" section in the readme #426 and then coordinate what goes there and what goes into wiki etc. with this current issue.

**Comment by LtSalt** [comment]
I was missing information on the git workflow. There is a minimal description, but as someone who is just starting to collaborate with others, I'd want to make sure I am not wreaking havoc on the project and following best practices.

**Comment by jstet** [comment]
I will close this for now as collaboration is working at the moment
