### ISSUE TITLE
Mobile Menu on Samsung S10 broken

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#432]
![Screenshot_20230525_205232_Firefox.jpg](https://github.com/CorrelAid/correlaid_website/assets/67161972/b272f510-c5ab-46a1-9403-bb2f3e58f3ae)

**Comment by jstet** [comment]
I cant reproduce the bug by simulating this format in the desktop browser (not on local nor on correlaid.org)

**Comment by jstet** [comment]
seems to be an issue with dvh

**Comment by LtSalt** [comment]
Which browser? I have no problem accessing it via a fairphone (firefox).

**Comment by jstet** [comment]
firefox

**Comment by jstet** [comment]
I updated my browser and now it works.

However should we use dvh if its not supported on older browser version?
