### ISSUE TITLE
Circles as icons educational ressources

### ISSUE THREAD

**Issue by ZoeWolter** [CorrelAid/correlaid_website#451]

**Comment by jstet** [comment]
Removed the image for now. Not sure how to implement this.

![edu-ressources-en](https://github.com/CorrelAid/correlaid_website/assets/67161972/1de3b752-b333-4a3e-869d-707ec3946538)

@ZoeWolter i also feel like the image feels a bit random. maybe we can add some text to describe what it means? are these the areas we offer workshops in?

**Comment by ZoeWolter** [comment]
@jstet Yes, exactly, those are the workshop topics overall, I feel like the page needs some visualization since there's quite a lot of text

**Comment by jstet** [comment]
@ZoeWolter would you still like this to be implemented? Personally I feel like the text/viz ratio is ok atm

**Comment by ZoeWolter** [comment]
The buttons are already on the website, right? For me it's fine like that!
