### ISSUE TITLE
Nav Icons Font and Colours

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#452]
Thanks! I like the elements and think that they could be useful on other pages. 

Looking at them on my big ass monitor screen, i have two concerns:

- font: i don't think the font is well readable from an accessibility perspective when it is so small. i know we have been using it on canva for a bit but i feel for this, it is not so well suited (the letters "mush together" even for me). 
- colors: maybe we could think about different colors for the backgrounds of the icons? I think right now it implies too much of a "sequence". in `[correltools](https://github.com/CorrelAid/correltools)` , there the opportunity to create qualitative palettes: 

```
scales::show_col(correltools::correlaid_pal()(5))
```

![Screenshot 2023-05-31 at 15 37 10](https://github.com/CorrelAid/correlaid_website/assets/13187448/c49a0b47-bee2-48ac-9e34-096538de041f)

or is this too many different colors? IDK.

_Originally posted by @friep in https://github.com/CorrelAid/correlaid_website/issues/448#issuecomment-1570261981_

**Comment by jstet** [comment]
@friep i have increased the font spacing, size etc. Does it work better now?

I intentionally used a sequence of colours so it fits to the gradient of the hero etc.

**Comment by friep** [comment]
where can i find this preview? sorry a bit slow today... :/

**Comment by jstet** [comment]
its on correlaid.org now because the content change required blocked other changes (see pr) thats why i opnned this issue

**Comment by friep** [comment]
lgtm
