### ISSUE TITLE
Promise issue on Data4Good page

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#466]
There currently is an issue on the data4good prject page, whcih is causing the CD errors found in #461.

This might be related to #389. In case it is a directus issue it should be made sure that all parsing etc. is done build time.

**Comment by KonradUdoHannes** [comment]
The underlying issue seems to be that the project with id `2019-02-MIN` has an associated post without a translation (and therefore no slug).

**Comment by friep** [comment]
![Screenshot 2023-06-07 at 14 36 17](https://github.com/CorrelAid/correlaid_website/assets/13187448/20191817-a094-4079-b008-64f6807622a7)

i checked and the post has a translation (and there is also no additional translation which was sometimes an issue..).

**Comment by KonradUdoHannes** [comment]
@friep Thanks for checking. It turned out that the issue was a pre-existing bug on the webpage itself that was only now triggered as we now had directus data triggering that case. It is fixed now.
