### ISSUE TITLE
Anonymize data for projects server side

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#469]
for projects where status == `published_anon`:

### organization data
only keep sector and legal form 

respectively: 
- org.short_id = null
- org.translations = [] // deletes description, website 
- org.id = null

### project outputs
set to [] (avoid spilling information contained in those)

### blog posts 
set to [] (dito)

### podcast
set to [] (dito)

### project people 
set to []
 
the last three are just a precaution - this shouldn't happen that we have a podcast episode and have to anonymize. but better be safe than sorry :) 

follow up to #457

**Comment by KonradUdoHannes** [comment]
From a general safety perspective I would suggest to implement the such that it whitelists what should not be anonymized, rather than blacklisting what should be. If the default is anonymous accidental exposure of sensitive information is a little less likely. The downside is of course that a project might more easily be anonymous by mistake, but I would expect this to be less critical.

**Comment by friep** [comment]
agree on whitelisting 💯

**Comment by friep** [comment]
here's the construction of the project objects:

```
  let new_objs = [];
      // for each project
      projects.forEach((proj) => {
        // extract whether project is anonymized
        let is_anon = proj.status == "published_anon";

        // flatten organizations and LCs
        proj.Organizations = [...proj.Organizations.map((o) => o.Organizations_id)];
        proj.Local_Chapters = [
          ...proj.Local_Chapters.map((o) => o.Local_Chapters_id),
        ];
        // filter out not public outputs
        proj.Projects_Outputs = proj.Projects_Outputs.filter(
          (out) => out.is_public
        );

        // anonymize People, Posts, Outputs, Podcast
        proj.Projects_Outputs = is_anon ? [] : proj.Posts;
        proj.Posts = is_anon ? [] : proj.Projects_Outputs;
        proj.People = is_anon ? [] : proj.People;
        proj.Podcast = is_anon ? null : proj.Podcast;

        let orgs = [];
        // organizations
        proj.Organizations.forEach((org) => {
          let reduced_org = new Object();

          reduced_org.id = is_anon ? -99 : org.short_id;
          reduced_org.short_id = is_anon ? "ANO" : org.short_id;
          reduced_org.legal_form = org.legal_form;
          reduced_org.sector = org.sector;

          if (is_anon) {
            reduced_org.translations = [];
          } else {
            reduced_org.translations = org.translations.map((trans) => {
                return { 
                	name: trans.name,
                  	website: trans.website,
                  	description: trans.description
                }
            });
          }

          orgs.push(reduced_org);
        });
        proj.Organizations = orgs;

        // local chapters
		proj.Local_Chapters = proj.Local_Chapters.map((lc) => {
            return { short_id: lc.short_id, founded: lc.founded } 
        });
          
        // translations
          
        if (is_anon) {
            proj.translations = proj.translations.map((trans) => {
                return { title: trans.title, summary: trans.summary }
            });
        } else {
            proj.translations = proj.translations.map((trans) => {
                return { title: trans.title, summary: trans.summary, description: trans.description }
            });
        }
          
          
        // returning new object
        let proj_obj = (({
          id,
          status,
          start_date,
          end_date,
          project_status,
          team_size,
          is_internal,
          data,
          type,
          language,
          Organizations,
          Projects_Outputs,
          Podcast,
          People,
          Posts,
            translations
        }) => ({
          id,
          status,
          start_date,
          end_date,
          project_status,
          team_size,
          is_internal,
          data,
          type,
          language,
          Organizations,
          Projects_Outputs,
          Podcast,
          People,
          Posts,
            translations
        }))(proj);

        new_objs.push(proj_obj);
      });
```

**Comment by friep** [comment]
please refactor for better code - my javascript skills are super rusty!

**Comment by friep** [comment]
yes, there will be more projects like this (actually probably the majority of projects..) 

re design: related is #231 where Jonas and me discussed the separate page. we would then link from the `daten-nutzen` page to the other page which would also get its own dropdown menu entry. there we had discussed that each project would get a subpage due to the amount of space needed even for anonymous projects (e.g. the project summary can get quite long). 

definitely this issue is only for adopting the server side code. I assumed you could complete this independently (e.g. by filtering client-side for `published` ) before doing client side things like design.

**Comment by friep** [comment]
from what i understand, this lgtm. in the future ( #231 ) , we'd need the `sector` and `legal_form` of the organization even if anonymized. however i think this is something that can be added later on when working on this. 

the slug is actually interesting because so far, they were the project ids (e.g. 2020-03-ERL), with the last three letters typically having some sort of relation to the organization (in the example, ERLassjahr). sometimes this would be very apparent, e.g. if it was Arbeiterwohlfahrt -> AWO. this is why i have left them out so far. but I think i'll just give out new IDs to those projects that focus more on the content. 

LCs not fetching those projects yet is ok for me. 

from my POV we can close this issue.

**Comment by KonradUdoHannes** [comment]
Ok then lets close this for now. I'm also in favor of parsing and potentially anonymizing additional fields once they become relevant, i.e. when implementing #231 for instance.
