### ISSUE TITLE
Publish project data as open data

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#470]
using a directus flow, do the following each night or on request from within the directus GUI

## implementation
- [x] anonymization based on status == "published_anon" (see #457 , #469 for logic)
- [x] metadata (last updated, ...)
- [x] publish a json to github repository (to be called `open-data`)

## documentation etc
- [x] license for data (cc by)
- [x] document for people within GUI what the new status means for the title and summary

**Comment by friep** [comment]
technical durchstich for directus -> github done. Data can now anonymized and pushed to github using a directus flow. 
waiting for #469 to implement their solution to improve code quality and double-check for logic errors.

**Comment by KonradUdoHannes** [comment]
As discussed in #469, it's implementation will not directly be applicable to the directus flow, but I'm happy to review the flow independently if needed.

**Comment by friep** [comment]
published here: https://github.com/CorrelAid/open-data/tree/main 

further "development" unrelated to the website issues in issues over there.
