### ISSUE TITLE
can't create new items in projects 

### ISSUE THREAD

**Issue by pr130** [CorrelAid/correlaid_website#475]
I can't create new items in the projects collection and could not update a certain one (2019-01-MAP). ended up deleting it and tried to recreate it but still got the same error.
See screenshot. 
@jstet maybe can you dig into the database and check whether there is indeed a duplicate ID? 
it's all very odd :( 

![Screenshot 2023-06-09 at 11 14 14](https://github.com/CorrelAid/correlaid_website/assets/13187448/fa0f14a8-d658-4206-abb2-dfa7497a0261)

**Comment by jstet** [comment]
I think this has happened before, I ll try to fix it now
https://github.com/CorrelAid/correlaid_website/issues/110

**Comment by jstet** [comment]
Yey easy fix. I dont know what causes this :S

**Comment by friep** [comment]
i wanted to recreate the project and turns out it was probably not an issue of the projects table... i can create the project without adding either Local Chapters or Organizations - when i try to do either i get the ID has to be unique error. 
When i go into the M2M collections, i find "dangling" entries. when i delete them, i can add the oragnization/LC.

**Comment by friep** [comment]
@jstet maybe you can try your "fix" for the Oragnizations_Projects collection? 🤔

**Comment by jstet** [comment]
''''
SELECT SETVAL('public."Organizations_Projects_id_seq"', (SELECT max(id) FROM public."Organizations_Projects"));
ALTER TABLE public."Organizations_Projects" ALTER COLUMN id SET DEFAULT nextval('"Organizations_Projects_id_seq"'::regclass);
''''
fixed it for organitations, but doing the same to LCs caused a different error that I am working on now

**Comment by jstet** [comment]
Nvm it worked as well, forgot the "id_seq"

**Comment by jstet** [comment]
"Fixed" it. @friep could you please confirm this and close this issue if you think this is resolved?

**Comment by jstet** [comment]
This occured again and the "fix" needs to be applied again

**Comment by jstet** [comment]
```

  defaultdb=> SELECT SETVAL('public."Organizations_id_seq"', (SELECT max(id) FROM public."Organizations"));
      118
  
  defaultdb=> ALTER TABLE public."Organizations" ALTER COLUMN id SET DEFAULT nextval('"Organizations_id_seq"'::regclass);
  ALTER TABLE
```
