### ISSUE TITLE
Feature: Add Ical link to follow events and RSS to subscribe to blog posts

### ISSUE THREAD

**Issue by tifa365** [CorrelAid/correlaid_website#487]
https://www.correlaid.org/en/events
https://www.correlaid.org/en/blog/

**Comment by KonradUdoHannes** [comment]
I think we should probably split this into two feature requests. Also on the technical side there is quite a difference between creating iCalender files and offer them for download and RSS. For RSS I think we would need to both create the files and provide a feed through wich they are obtained.

**Comment by KonradUdoHannes** [comment]
I checked the the proposed API route solution for static builds and it it works with svelte-kit. So routes such as 
`.../someCalendar.ics` can be defined with `+server.js` files of the form given below. I just pasted the content of an open calendar into the constant `CAL` for testing, but one can also define it dynamically.

RSS feeds should work the same just with the content type being replaced by xml.

```js
export const prerender = true;

export function GET() {

  return new Response(CAL, {
    headers: {
      'Content-Type': "text/calendar; charset=utf-8",
    }
  });
}
```

This means we can proceed with case specific discussions and technical implementations.

Issue for calendar(s): #493
Issue for RSS: #494

**Comment by tifa365** [comment]
Issue for calendar(s): #493
Issue for RSS: #494

**Comment by jstet** [comment]
@tifa365 rss feed is implemented now :)

**Comment by jstet** [comment]
ical link as well
