### ISSUE TITLE
Some old backlinks to correlaid.org are broken

### ISSUE THREAD

**Issue by tifa365** [CorrelAid/correlaid_website#488]
You can check here and get a sample: https://ahrefs.com/broken-link-checker

I suppose the new navigation structure of the page broke some links from the outside. I've only done this in WordPress but there is usually a tool with which you can re-route requests to the correct url.

For example, https://www.correlaid.org/en/correlaid-x/ could be rerouted to https://www.correlaid.org/en/community/correlaidx/

Could definitely not hurt the google ranking in the long term.

**Comment by KonradUdoHannes** [comment]
Thanks. I'll check out the tool you suggested.

Generally we already forward a lot of the old routes to new routes and cross checked this against external links listed by the google search console. The goal was not to have complete coverage for the old routes, but to not loose existing backlinks. Its probably a good idea to cross check with a separate tool to see whether something fell through the cracks.

**Comment by KonradUdoHannes** [comment]
I tried to crosscheck a few results from the tool you suggested with the results from the google search console, some other free tools and I tried to manually confirm the issues. For the most part I was not able to reproduce the broken back link issues suggested by ahrefs.org.

@tifa365 Did you have any concrete broken backlinks that you encountered?

So far the only broken back links that I could confirm are the following. Unfortunately I'm not sure why they don't show up in the google search console as inbound links (and hence were not checked preiviously).

- https://correlaid.org/de/events/2020-11/correlcon/
- https://correlaid.org/de/

**Comment by tifa365** [comment]
The aforementioned website listet 150 broken links. I cherry picked some of the results but also could not confirm the back links are not working. The only one I found was https://www.correlaid.org/en/correlaid-x/ not being redirected. I would close the issue in this case.
