### ISSUE TITLE
Project cards for internal projects

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#489]
Parsing of the project card information from directus should be modified such that the following two options are both valid.
- a project has an associated organization
- the `is_internal`  field is set to true and no organizations are provided.

This means parsing should still fail if `is_internal` is false and no organizations are provided or if `is_internal` is true and an organization is provided nonetheless.

The project card component needs to be modified to omit the organization icon and name for internal projects.

**Comment by KonradUdoHannes** [comment]
So far I tried two design options for project cards for the internal projects. They are
- Without any Org/Icon
- With the Correlaid Icon instead of the regular NPO Icon and the text "internal project"

I like the second option a little better because the design looks a little more consistent, whereas the first option looks like something might just be missing by accident. I also think it makes sense to make the internal projects visually different from the external ones. What I don't like so far is the contrast between the regular NPO logo and the CorrelAid Logo which I feel is a little too much, with one being black and the other quite bright.

@friep Any thoughts or preferences? If one design choice appears generally fine I would also suggest to just take it for now and tweak the logo separately. I'm inclined to go with the second one.

![image](https://github.com/CorrelAid/correlaid_website/assets/48182869/5058de46-c9d8-4ec5-89fe-d38d4ff93eb0)
![c_logo](https://github.com/CorrelAid/correlaid_website/assets/48182869/50e13677-e7fa-4064-9916-b7de8e0d2390)

**Comment by KonradUdoHannes** [comment]
The current page now also has the version deployed where "CorrelAid e.V." is simply given as an Organization. That also works well, but I think it would be nicer to distinguish more transparently and more visually between internal and external projects.

**Comment by friep** [comment]
I like the second version with the CorrelAid logo a lot. with the first version it looks a bit like we forgot to add the organization^^ thanks for deploying the interim solution though!

**Comment by KonradUdoHannes** [comment]
I'll deploy the version with the logo then. I also changed the requirement that internal projects cannot have an organization such that Inserting "CorrelAid e.V." as an organization does not cause an error, which is weird because the value is logically not wrong. However, any value put into organizations for internal Projecsts, will not be used for project cards.
