### ISSUE TITLE
Implement ical feeds for events

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#493]
This would be a nice way to stay on top of correlaid events by subscribing one's calendar to the feed url.

Open questions:
- [x] How many calendars should we have?
    - 1 For everything
    - 1 For each LC + 1 for non-lc events
    -  both of the above (for simpler subscription)
- [x] Do our events have uuids in directus that we can use for calendar creation?
- [x] What shall we use for the FTI string for correlaid in the Calendar (PRODID)?
    - Suggestion: -//CorrelAid//NONSGML CorrelAid Events V1.0//EN (see https://icalendar.org/iCalendar-RFC-5545/3-7-3-product-identifier.html) This is not crutial, but since its (partially) a technical organization identifier (see https://en.wikipedia.org/wiki/Formal_Public_Identifier). Consistency might only become relevant if CorrelAid uses similar identifers somewhere else, which I don't think is the case.

**Comment by jstet** [comment]
- I will try to implement a feed for each LC and one for global events, because it would be a nice  for people that don't have access to our google calendar to follow events of their LCs 
- no we dont have uuids in the strict sense (128-bit value)
- I will implement your suggestion re FTI string

**Comment by jstet** [comment]
Routes for global events will be events/ical and for local chapters e.g. volunteering/correlaidx/bremen/ical

**Comment by jstet** [comment]
We can deterministically create a uuid from the directus id

**Comment by jstet** [comment]
Ical feed was implemented, but now we need to find a way to display the possibility to subscribe to it.
Suggestions:
- icon near "events"
- add. icon in footer
- text under "Events" header

also for lc pages
