### ISSUE TITLE
Implement an RSS feed for the website

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#494]
This might be nice to help people follow what's going on at correlaid. The feed could start with blogposts, but might be extended to allow for other announcements. For instance newly released podcasts.

**Comment by jstet** [comment]
Resources:
- https://www.adamsanderson.co.uk/blog/2023-05-29-bring-rss-brack
- https://ghostdev.xyz/posts/creating-a-rss-feed-with-sanity-and-svelte-kit/

We could use the https://github.com/dylang/node-rss package

**Comment by jstet** [comment]
was implemented in #688 (wrong branch)
