### ISSUE TITLE
introduce "preview" status for content and corresponding site configuration options

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#500]
The following contents should have a "preview" state available for selection
- blog posts
- events
- jobs
- local chapters
- projects

The site should offer configuration options to either include or exclude "preview" content. This way local development and dev deployments can be configured to show preview content for the purpose of fine tuning it, whereas production can be configured to not show such content.

**Comment by jstet** [comment]
Does this idea originate from slack? :D 
someone was wondering about the unpublished posts not showing up in preview. I think this would indeed be a nice addition.

**Comment by KonradUdoHannes** [comment]
I'll split this up into subtasks so we can prioritize and finish them separately. The only connection I can think of right now is that we should give the "preview" state the same name across all content, but I think there is nothing speaking against literally calling it "preview".

- [ ] jobs #512
- [ ] blog posts #513
- [ ] events #514
- [ ] local chapters #515
- [ ] projects #516

**Comment by jstet** [comment]
Currently, the public and website_builder role can only see stuff that has "published" as its status. Because the preview status is relevant for almost all queries, i will allow the public role to see preview stuff. The website_builder role needs to have access anyways

**Comment by jstet** [comment]
On second thought, this would not be good for job posts for example..

I am going to add an if condition to the directus_fetch function so that it tries with token if its existent but without if not and add functionality that if PUBLIC_PREVIEW is true, DIRECTUS_TOKEN cant be empty.
