### ISSUE TITLE
Static build should include all assets

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#505]
The static build does currently not include all assets. The concrete example I noticed are images of People, which are still fetched from the cms. This means they are not available if the cms is unavailable.

It would be more consistent if the static build also includes the assets for the webpage.

This is not critical as assets are less important for the functionality of the website, but they are still very important for its appearance.

**Comment by KonradUdoHannes** [comment]
This seems to be less straight forward then I initially thought. Sveltekit offers to import assets stored in the project from `$lib/assets`, but the difficulty for including all the assets in a static build would then be to determine all the assets that need to be included, which is dynamic based on other content.

**Comment by jstet** [comment]
from time to time i worry about the stability of our directus instance (btw we should probably update the directus version from time to time and add some kind of monitoring idk) and decoupling images from it would reduce my worries :D

**Comment by jstet** [comment]
Images are fetched remotely, so we would have to find some way to download the images and also change the src attribute

**Comment by jstet** [comment]
https://kit.svelte.dev/docs/images

**Comment by jstet** [comment]
I think the best approach is to write a npm postbuild script to modify the output of the build
