### ISSUE TITLE
Language of Blog posts vs. General Language Settings

### ISSUE THREAD

**Issue by tifa365** [CorrelAid/correlaid_website#506]
When I read through a couple of blog posts today, I became a bit confused what the overall system is of providing blog posts in different languages? I am sorry if this was already discussed, I could not find the post.

1. Depending on general language setting of English or German, do * not * show blog posts of other language. For each language, some articles will be 'lost.' 

2. Global language setting German or English: Show all blog post languages in English and German regardless of global language chosen (this could be confusing).

3. Depending on general language setting of English or German, enforce automatic translation according to global language setting, e.g. using deepl. This could lead to quality problems in the translation but makes sure all blog posts are available in all languages. A note could be added the blog post was translated.

**Comment by jstet** [comment]
The system is what you mentioned in 2. 

A language indicator is shown for which language is available for posts. But as you wrote in https://github.com/CorrelAid/correlaid_website/issues/507 this is buggy atm. If this works, would this reduce your confusion?

**Comment by tifa365** [comment]
I think I would be fine with any of these solutions but the bug mentioned in #507 threw me off. Will be closing this issue.
