### ISSUE TITLE
Blog posts: Language icon in the right corner of the preview post is always English

### ISSUE THREAD

**Issue by tifa365** [CorrelAid/correlaid_website#507]
A bit unclear whether the button defines the articles can be translated to another language or if it marks the original language - but even German posts are marked as English?

![correlaid](https://github.com/CorrelAid/correlaid_website/assets/66328500/f501c190-50a2-4c0f-8f7e-226b9e8881de)

**Comment by jstet** [comment]
Yea this seems to be a bug. It worked before so maybe an issue with the newly added server side rendering
