### ISSUE TITLE
Accessibility: dont use aria labels for non-interactive elements

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#510]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

Example for correct usage:
```
<span aria-hidden="true">[Watch icon HTML here]</span>
<span class="sr-only">Event start time</span>
```

**Comment by KonradUdoHannes** [comment]
Regarding the emojis, I think we would have probably been fine without the aria labels as a screen ready would have read for instance "round pushpin" for the location icon as that is the name of the emoji. I think the required associations in this case are then similar to the associations that regular users do when associating the emoji image with the context.
But with aria labels in place, replacing emojis with SVGs to address #519 got even simpler.
