### ISSUE TITLE
Add more project output types to projects card

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#511]
This project (https://cms.correlaid.org/admin/content/Projects/101) has two public outputs but they are not shown on the card.

**Comment by KonradUdoHannes** [comment]
I had a quick look, and I'm not sure whether this was ever supported and got removed by accident, but currently there is simply no support implemented for more than one external link at once. Additional external links are ignored.

Its probably most efficient to implement the feature from scratch. If it existed in the pasts its too many restructurings ago that the features simplicity does not warrant to search for it in the commit history for too long (an potentially not finding it).

**Comment by jstet** [comment]
yes i think we agreed to only display certain types of outputs until we implement the projects database

**Comment by friep** [comment]
could we prioritize this before #231 ? given that #231 will probably take a bit longer in development?

**Comment by jstet** [comment]
@friep  How do you suggest we implement external links? Should the name of the additional links correspond to the output types? how do we deal with "other..". should it the  say smth like: "Other Output"?

**Comment by friep** [comment]
In the translations there should be a field "description"...but yeah maybe a bit long for the cards. How many "others" are there?

**Comment by jstet** [comment]
> could we prioritize this before #231 ? given that #231 will probably take a bit longer in development?

I suggest to directly implement this in the new project db page as i think i will be finished with it relatively soon.

**Comment by jstet** [comment]
will implement this in V1 of #231
