### ISSUE TITLE
Uniform usage of icons (svgs and/or emojis)

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#519]
Split of from #495 with the below quote from that issue. The issue is currently concerned with the svgs founds in the event slug pages and the emojis used in job cards and on job slug pages.

> I was also wondering about unifying our icons. But am wondering about the following considerations. @jstet what are your thoughts on this.
>
> - The svgs seem to have the disadvantages
>     - we have to get them somewhere (do we have a good source?)
>     - They generate a little bit more clutter in the codebase with extra files and imports which makes it more complex to add a new one.
> - Emojis have the disadvantages
>     - doesn't scale at will (but scales with font size. Doe we realy need more)
>     - Less Control over the exact appearance (for instance color)
>
> With these considerations I'm not sure of what's actually the better choice. But I think if we decide for svg we should document the creation/process for the svgs so we could easily keep it uniform in the future.

There are possibly also conidiation regarding accessibility. SVGs my need explicit aria lables more often, whereas emojis might not as long as the emojis name aligns with the meaning that the icon is supposed to covey on the website.

**Comment by jstet** [comment]
- So far i used https://thenounproject.com for svgs. I have a subscription, so we can freely use all icons.
- Yes they do indeed add clutter to the code base, but i feel like this is outweighed by the customizability they offer.
- we have used svgs so far and it would be a lot of work to switch to emojis. 
- svg need more accessibility info yes, but its not that much work to add

**Comment by jstet** [comment]
As the the large majority of icons are currently svgs, I will change the icons in job pages to svgs as well
