### ISSUE TITLE
Projects Database: use dashboard like presentation (wider page ?)

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#528]
Open discussion

**Comment by friep** [comment]
pro: could have separate "tab" for "analytics"

**Comment by jstet** [comment]
We also need to think about how to implement this on mobile

**Comment by jstet** [comment]
So my suggestion is the following: We keep it like it is atm but add a tab selection below the filter. Tab 1 is the list of projects, tab 2 is "analytics". Analytics will contain graphs that are responsive to the filter. 

One graph could be a line graph that visualizes the development of the number of projects and displays the total number of projects (based on filter) at the end of the line. Other graphs could visualize the distribution of projects status, local chapters, sector of organization etc. 

I am opposed to using a wider presentation, because this would disrupt the normal page width of the website (introducing a one time exception) and require thinking about how to do it differently on mobile.

**Comment by jstet** [comment]
See #471 
We will keep it like it is atm
