### ISSUE TITLE
Education Resources: add tooltip to display more text, add external link icon

### ISSUE THREAD

**Issue by ZoeWolter** [CorrelAid/correlaid_website#535]
@jstet I've just recognized that you can just see the first three lines of the description and as the links directly lead to Github or the like, the full text is actually nowhere. Any ideas? Maybe with a tooltip?

**Comment by jstet** [comment]
Yea tooltip would be a good option

**Comment by jstet** [comment]
External Link Icon was added already

**Comment by jstet** [comment]
I am going to try and implement a collapse/extend functionality for the cards
