### ISSUE TITLE
Deletion of azure directus resources

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#546]
The Azure resource group containing the Directus Backend including backups of the content and config was deleted accidentally. 
So because of #505, website does not contain images atm. 
This effectively halts website development until we have restored the backend.
I will start working on this today at like 4pm. Ill begin by posting an overview of what needs to be restored. 
Maybe we can use this chance to improve some things idk. Ill work on the infrastructure in a sep. repo.

**Comment by jstet** [comment]
infrastructure is up (iac in external repo)

**Comment by jstet** [comment]
-Workshops: https://github.com/CorrelAid/correlaid_website/issues/557

**Comment by jstet** [comment]
- Awards: https://github.com/CorrelAid/correlaid_website/issues/560

**Comment by jstet** [comment]
- Global Admins: https://github.com/CorrelAid/correlaid_website/issues/562

**Comment by KonradUdoHannes** [comment]
@jstet with #551 done as the last linked issue, i think we can close this one.

**Comment by jstet** [comment]
- [ ] One last thing to do is republish the website, afterwards I'll close this
