### ISSUE TITLE
Scrape Website to fill Podcasts in CMS

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#550]

**Comment by KonradUdoHannes** [comment]
I generally filled the podcasts with the following aspects still missing
- content creators
- image(s)
- translations aspects (not too may on this page I think)

@jstet @friep I think wrt. to images all the podcasts have the same image so if we can add it again that would make it very simple. I can actually do it myself for a very curious reason that I wanted to point out. The old image link
[https://cms.correlaid.org/assets/51fc6c55-be78-48a8-a201-aa8d5e8105e1?](https://cms.correlaid.org/assets/51fc6c55-be78-48a8-a201-aa8d5e8105e1?) on the production website still works, which is very weird because even if we had added the image again it should have gotten a different UUID (I also don't see it under files). Also the link only works with the trailing `?` even though that, i.e. an empty query string, should not make a difference.

**Comment by KonradUdoHannes** [comment]
Also outstanding is systematic implementation of all the standards in our "Directus Collection Standard". This mainly includes presentation within directus itself including comments for content creators.

**Comment by jstet** [comment]
This seems to be finished
