### ISSUE TITLE
Scrape Website to fill Events in CMS

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#551]

**Comment by KonradUdoHannes** [comment]
I added events with the following things still outstanding.
- links to local chapters
- translations where applicable (Not so many for events)

**Comment by KonradUdoHannes** [comment]
Also outstanding is systematic implementation of all the standards in our "Directus Collection Standard". This mainly includes presentation within directus itself including comments for content creators.

**Comment by friep** [comment]
is this finsihed?

**Comment by friep** [comment]
i'd propose the following changes to the schema:

- description as wysiwyg 
- do translation for description instead of language field? Although i'm not sure how this was implemented
- dropdown with options for target group and type
- location as geo field? 

@jstet maybe you remember more about it?

**Comment by KonradUdoHannes** [comment]
> is this finsihed?

Not quite. I think the local chapter links are still missing. I havn't gotten back to this since LCs have been done. This includes the translation aspect I mentioned above as the LCs are the only thing in the current schema that introduces translations to the fetching of events.

**Comment by KonradUdoHannes** [comment]
> i'd propose the following changes to the schema:
> 
> * description as wysiwyg
> * do translation for description instead of language field? Although i'm not sure how this was implemented
> * dropdown with options for target group and type
> * location as geo field?
> 
> @jstet maybe you remember more about it?

In case we make schema changes let me know so we can re-use the script to populate the modified schema. 

- Regarding language and translations I think there is a difference. I understand the forma as the language of the event whereas the latter is related to different language versions for content on our website.
- For location as a geo field I'm not sure whether its a sensible replacement because the geo fields are more technical and our current field is a little more verbose and human readable. If there is a practical way to extract a readable string (like an address) from the geo location that would be fine though. Otherwise we could also consider optionally providing the geo field in addition to a readable location field and for instance link to open street map coordinates when clicking on location.

**Comment by jstet** [comment]
>     * description as wysiwyg
> 
- [ ] I will change this in directus now.

>     * do translation for description instead of language field? Although i'm not sure how this was implemented
> 
as Konrad already wrote, the language field is for the language of the event. 
>     * dropdown with options for target group and type
> 
- [ ]  yes we had it like that in the past, I will change it now
>     * location as geo field?
> 
I agree with Konrad, we don't really need this field to contain coordinates. Using coordinates would require extra work in svelte

**Comment by jstet** [comment]
@KonradUdoHannes changed the schema as specified above

**Comment by KonradUdoHannes** [comment]
Ok I'll get going on reinserting the descriptions.

**Comment by KonradUdoHannes** [comment]
Descriptions, target group and type should already be present again. I'll still need to include the links to the LCs. I'll close the issue once this is don.

**Comment by jstet** [comment]
- [ ] sry one further change: language should be a dropdown not a simple input field

**Comment by KonradUdoHannes** [comment]
Inserted LCs to events. Language was also replaced by  a dropdown field an reinserted. This concludes this issue.
