### ISSUE TITLE
Scrape Website to fill public Projects in CMS

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAid/correlaid_website#554]

**Comment by friep** [comment]
i'd actually use the dump that i have and make the rest of adjustments that had happened in the meantime manually

**Comment by jstet** [comment]
Blog Posts and Podcast links seem to be missing sometimes, for example for 2018-11-TVK

**Comment by friep** [comment]
added missing podcast link for beeobserver (links for TVK project were not correct)
