### ISSUE TITLE
Making support for CorrelAid more present

### ISSUE THREAD

**Issue by IsabelWi** [CorrelAid/correlaid_website#582]
We should make the option to support CorrelAid financially more present on the website, perhaps a separate tab in the menu. There we should also specify what we want to achieve with the money (see Betterplace profile). The idea behind it: People who come to betterplace actually already know that they want to donate and would probably get the information on how and for what in advance.

**Comment by PatMaier92** [comment]
@jstet I just added you to our Betterplace account. Here you can find premade code by Betterplace for the buttons, widgets, etc. As Isabel already pointed out, it would be good to 1) use the larger "Projekt-Widget" button on the website front page instead of the small one that we currently use and also 2) add an extra tab "Unterstützen" with the "Spendenformular" embedded. For the extra tab we would 3) need to supply you with some text about what we want to achieve with the money (tbd).

**Comment by jstet** [comment]
Please confirm if the following is what you meant:

**Comment by jstet** [comment]
Please confirm if implementing the following is suitable to achieve what you meant:

- [ ] Replace the "Donate" button in the upper left corner with a "Support CorrelAid" button 
- [ ] Create a Page (reachable through click on Support Button) containing info on how to support CorrelAid and links to further pages (Spendenformular)?
- [ ] Create a page that embeds the Spendenformular so that poeple can directly donate on the CorrelAid Website (reachable throguh support page)
- [ ] Add the betterplace widget to the bottom of the front page of correlaid.

**Comment by PatMaier92** [comment]
@IsabelWi feel free to add your comments! Maybe it would be wise to get some other opinions, too ...

I would suggest: 
1. Replace the "Spenden/Donate" button with the "Projekt Widget" from Betterplace. Clicking on this leads directly to Betterplace. 
![grafik](https://github.com/CorrelAid/correlaid_website/assets/59774707/54ccb5da-4baa-4e5f-b138-60b304c8f172)
2. Create a new tab "Unterstützen/Support" next to the Veranstaltungen, Blog, Podcast, Newsletter tabs. Clicking on "Unterstützen/Support" leads to a new page containing info on how to support CorrelAid and the Spendenformular. 
3. Yes, can be combined with 2. 
4. In my personal opintion, it would be better to have the Widget at the top for maximum visibility, see 1.

**Comment by jstet** [comment]
> I would suggest: 
> 1. Replace the "Spenden/Donate" button with the "Projekt Widget" from Betterplace. Clicking on this leads directly to Betterplace. 

I feel like the Navbar is too small in height for the widget. 


> 2. Create a new tab "Unterstützen/Support" next to the Veranstaltungen, Blog, Podcast, Newsletter tabs. Clicking on "Unterstützen/Support" leads to a new page containing info on how to support CorrelAid and the Spendenformular. 

If we replace the Donate Button with a Support Button, we can avoid overcrowding the main navbar.

**Comment by IsabelWi** [comment]
Hmm, I understand your objections about the navbar, jonas. Would it be an idea to put the widget under (web view) or next to (mobile view) the 3 landing page buttons? It would certainly look less stylish, but perhaps not quite as bad? Furthermore, as Patrizia writes (2.) I would definitely add the tab at the top next to blog, podcast, etc. In addition, I would keep the "old" donation button. I realise that the widget will probably be too big at that point....

**Comment by jstet** [comment]
If we add an extra title to the top navbar, keep the old donation button and add the widget to the front Page, we'd have three visible options where ppl can donate when they enter the page. I feel like this is too "in your face". Personally, I think the solution to have one highlighted "Support" button that leads to a page that directs people to the right places is the most elegant option.

 We could place the widget on the about us page maybe?

**Comment by IsabelWi** [comment]
So you wouldn't add an extra tab to the navbar? 
All 3 things are probably really a bit too much. However, I think an entry at the top of the navbar with "untersützen" is good, as the member form is better placed there than underneath Community at the moment. And I would still keep the donation button as a "shortcut". Do you think both of these are too much?

**Comment by PatMaier92** [comment]
Fair point Jonas! Ok I think it's best if we discuss the options in the board meeting with some more people and I will let you know after the meeting what people like/dislike. Especially regarding the "Support" tab (e.g. for donation form and member form) and the distinction of this tab to "Community" (one idea I just had: rename Community to Support?). The main goal ist to make the support stuff more visible/salient without making it confusing or too pushy.

**Comment by jstet** [comment]
Alright, then I'll w8 with the implementation till then

**Comment by jstet** [comment]
Last update was to create a mock up in canvas first.

**Comment by jstet** [comment]
I will transform this issue into what the current plan looks like:

Unterseite, erreichbar über "Unterstützen" Button. Ähnlich wie Newsletter.

Zwei Items:

- Spenden über Betterplace
- Fördermitgliedschaft via twingle

https://docs.google.com/document/d/14-xcWe6g_6iUO3xcKQI2qXvjcylsmxWnYIMJ_oOvWBo/edit?tab=t.0
