### ISSUE TITLE
Allow for project subpages without description

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#632]
related to #621 

if we keep the summaries as an option to have a middle ground between "project with long description" and "project without any description" it'd be good to be able to display a subpage for those projects even though it might be very minimal.
right now, the build fails because description can't be empty.

**Comment by jstet** [comment]
Will work on this after https://github.com/CorrelAid/correlaid_website/issues/621 is closed

**Comment by jstet** [comment]
Already implemented
