### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#68]
- [ ] Overview Design
- [ ] Single Page Design
- [ ] Content
- [ ] Collection (Events)

**Comment by jstet** [comment]
Man könnte das vorläufig über ein Skript machen, das mehrere regelmäßige Events gleichzeitig erstellt @friep 
ich würde kompliziertere Funktionen was die Events Collection und das Handeln im Frontend betrifft auf nach den Release der ersten Version verschieben. Vielleicht bekommt man es sogar irgendwie hin, die Collection mit Google Calendar zu synchronisieren.

**Comment by friep** [comment]
ja , skripten ginge auf jeden fall 💯 gute Idee! kann eine github action sein oder ueber das flows abgedeckt werden?!
