### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#75]
- [ ] Design
- [ ] Content

**Comment by jstet** [comment]
@IsabelWi das Carousel war ja ursprünglich vor allem für die Community-Seite geplant und ausgehend davon habe ich das auch zu den anderen Übersichtsseiten hinzugefügt. Was ist jetzt der Plan für Community? Soll das Carousel dort bleiben oder auch entfernt werden? Vielleicht an eine andere Stelle oder mit anderen Slides, die nicht den Subpages entsprechen?

**Comment by IsabelWi** [comment]
Hi @jstet, ad hoc würde ich sagen, dass ich es gern behalten möchte, bei den anderen Seite wurde das jetzt abgeschrieben? Ich finde es würde immer noch gut in die Seitenlogik passen, aber abschließend beurteilen kann ich das denke ich, wenn die Inhalte stehen und ich das einmal mit Bildern gefüllt sehe. Ich will mich damit ab Freitag auseinandersetzen.

**Comment by jstet** [comment]
Ja beim retreat wurde beschlossen, für übersichtsseiten kein carousel mehr zu benutzen, weil das als navigation redundant sei und die horizontal angeordneten titel mobile schlecht sind.
