### ISSUE TITLE
RSS link/guide "undefined"

### ISSUE THREAD

**Issue by stroebjo** [CorrelAid/correlaid_website#774]
In the RSS feed (https://www.correlaid.org/rss.xml) the `link` and `guid` of entries are set to `https://correlaid.org/blog/undefined`. There seems to be some issue in getting the article slug which leads to `undefined` being set into the URL.

Also the entry description only contains only the teaser and not the full post content. Was this an intentional choice? Would be nice to get the full content in RSS readers. :)

**Comment by jstet** [comment]
Hey,
thanks a lot for reporting this bug! Nice to hear that people are actually using the RSS feed :) 

I didn't have that much experience with RSS so somehow I must have thought that usually entries in RSS feeds are only previews. But that doesn't make and I'll adjust it.
