### ISSUE TITLE
Further improve project database

### ISSUE THREAD

**Issue by tifa365** [CorrelAid/correlaid_website#791]
Referring to https://www.correlaid.org/daten-nutzen/projektdatenbank/:

- On mobile the titles of certain projects are sometimes so long that they overlap with the looking glass icon on the right
- A text description (of the project search functionality) on top of the page could further improve the Google ranking. Right now, the page begins with the search mask
- it would be very cool to be able to make the keyword boxes under each project heading clickable and thus sort by keyword. I did not visit the page for quite some time, and the coloring of the boxes makes you think these are interactive elements.
- Searching by keyword could also be added to the search box

**Comment by jstet** [comment]
Thanks for opening the issue! I will split this issue into three issues and work on your first two points right away

**Comment by jstet** [comment]
https://github.com/CorrelAid/correlaid_website/issues/800

**Comment by jstet** [comment]
I have added a text in the CMS. it will be online when the next page build occurs

**Comment by jstet** [comment]
I assumed you meant the organization name that was overlapping with the icon and not the title itself. I have added some margin to the right to adjust the  former. The latter is overlapping on the x axis but as it is below it, this should be fine.

I will close this issue now and track progress of the other points in the corresponding issues
