### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#8]
- [ ] Design
- [ ] Content

**Comment by friep** [comment]
ich wuerde vorschlagen für v1, damit wir da nciht auch noch content fuer machen (dann lieber nochmal gut ueberlegen):

buttons zu drei landing pages (im hero?): 
- Daten nutzen
- Bildung
- Community 

Call to Action: Datensprechstunde
Call to Action: Onboarding Call

upcoming events

latest podcast episodes

latest blog posts
